//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.13 at 09:39:00 AM EEST 
//


package com.gillsoft.client;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trip" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="routemap">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="route" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="time_arr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="time_dep" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                     &lt;attribute name="st_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="st_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="time_dep" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="st_dep_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="st_dep_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="st_form_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="st_form_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="st_end_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="st_end_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="period" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="bus_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="bus_capacity" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="hash" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trip"
})
public class Schedule {

    protected List<Schedule.Trip> trip;
    @XmlAttribute(name = "hash")
    protected String hash;

    /**
     * Gets the value of the trip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Schedule.Trip }
     * 
     * 
     */
    public List<Schedule.Trip> getTrip() {
        if (trip == null) {
            trip = new ArrayList<Schedule.Trip>();
        }
        return this.trip;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="routemap">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="route" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="time_arr" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="time_dep" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                           &lt;attribute name="st_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="st_code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="time_dep" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="st_dep_code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="st_dep_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="st_form_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="st_form_code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="st_end_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="st_end_code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="period" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cat" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="bus_name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="bus_capacity" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "routemap"
    })
    public static class Trip {

        @XmlElement(required = true)
        protected Schedule.Trip.Routemap routemap;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "number")
        protected String number;
        @XmlAttribute(name = "time_dep")
        protected String timeDep;
        @XmlAttribute(name = "st_dep_code")
        protected String stDepCode;
        @XmlAttribute(name = "st_dep_name")
        protected String stDepName;
        @XmlAttribute(name = "st_form_name")
        protected String stFormName;
        @XmlAttribute(name = "st_form_code")
        protected String stFormCode;
        @XmlAttribute(name = "st_end_name")
        protected String stEndName;
        @XmlAttribute(name = "st_end_code")
        protected String stEndCode;
        @XmlAttribute(name = "period")
        protected String period;
        @XmlAttribute(name = "cat")
        protected String cat;
        @XmlAttribute(name = "bus_name")
        protected String busName;
        @XmlAttribute(name = "bus_capacity")
        protected Integer busCapacity;

        /**
         * Gets the value of the routemap property.
         * 
         * @return
         *     possible object is
         *     {@link Schedule.Trip.Routemap }
         *     
         */
        public Schedule.Trip.Routemap getRoutemap() {
            return routemap;
        }

        /**
         * Sets the value of the routemap property.
         * 
         * @param value
         *     allowed object is
         *     {@link Schedule.Trip.Routemap }
         *     
         */
        public void setRoutemap(Schedule.Trip.Routemap value) {
            this.routemap = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumber(String value) {
            this.number = value;
        }

        /**
         * Gets the value of the timeDep property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimeDep() {
            return timeDep;
        }

        /**
         * Sets the value of the timeDep property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimeDep(String value) {
            this.timeDep = value;
        }

        /**
         * Gets the value of the stDepCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStDepCode() {
            return stDepCode;
        }

        /**
         * Sets the value of the stDepCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStDepCode(String value) {
            this.stDepCode = value;
        }

        /**
         * Gets the value of the stDepName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStDepName() {
            return stDepName;
        }

        /**
         * Sets the value of the stDepName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStDepName(String value) {
            this.stDepName = value;
        }

        /**
         * Gets the value of the stFormName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStFormName() {
            return stFormName;
        }

        /**
         * Sets the value of the stFormName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStFormName(String value) {
            this.stFormName = value;
        }

        /**
         * Gets the value of the stFormCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStFormCode() {
            return stFormCode;
        }

        /**
         * Sets the value of the stFormCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStFormCode(String value) {
            this.stFormCode = value;
        }

        /**
         * Gets the value of the stEndName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStEndName() {
            return stEndName;
        }

        /**
         * Sets the value of the stEndName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStEndName(String value) {
            this.stEndName = value;
        }

        /**
         * Gets the value of the stEndCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStEndCode() {
            return stEndCode;
        }

        /**
         * Sets the value of the stEndCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStEndCode(String value) {
            this.stEndCode = value;
        }

        /**
         * Gets the value of the period property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeriod() {
            return period;
        }

        /**
         * Sets the value of the period property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeriod(String value) {
            this.period = value;
        }

        /**
         * Gets the value of the cat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCat() {
            return cat;
        }

        /**
         * Sets the value of the cat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCat(String value) {
            this.cat = value;
        }

        /**
         * Gets the value of the busName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBusName() {
            return busName;
        }

        /**
         * Sets the value of the busName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBusName(String value) {
            this.busName = value;
        }

        /**
         * Gets the value of the busCapacity property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBusCapacity() {
            return busCapacity;
        }

        /**
         * Sets the value of the busCapacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBusCapacity(Integer value) {
            this.busCapacity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="route" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="time_arr" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="time_dep" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                 &lt;attribute name="st_name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="st_code" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "route"
        })
        public static class Routemap {

            protected List<Schedule.Trip.Routemap.Route> route;

            /**
             * Gets the value of the route property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the route property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRoute().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Schedule.Trip.Routemap.Route }
             * 
             * 
             */
            public List<Schedule.Trip.Routemap.Route> getRoute() {
                if (route == null) {
                    route = new ArrayList<Schedule.Trip.Routemap.Route>();
                }
                return this.route;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="time_arr" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="time_dep" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="distance" type="{http://www.w3.org/2001/XMLSchema}short" />
             *       &lt;attribute name="st_name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="st_code" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Route {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "time_arr")
                protected String timeArr;
                @XmlAttribute(name = "time_dep")
                protected String timeDep;
                @XmlAttribute(name = "distance")
                protected Short distance;
                @XmlAttribute(name = "st_name")
                protected String stName;
                @XmlAttribute(name = "st_code")
                protected String stCode;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the timeArr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTimeArr() {
                    return timeArr;
                }

                /**
                 * Sets the value of the timeArr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTimeArr(String value) {
                    this.timeArr = value;
                }

                /**
                 * Gets the value of the timeDep property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTimeDep() {
                    return timeDep;
                }

                /**
                 * Sets the value of the timeDep property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTimeDep(String value) {
                    this.timeDep = value;
                }

                /**
                 * Gets the value of the distance property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Short }
                 *     
                 */
                public Short getDistance() {
                    return distance;
                }

                /**
                 * Sets the value of the distance property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Short }
                 *     
                 */
                public void setDistance(Short value) {
                    this.distance = value;
                }

                /**
                 * Gets the value of the stName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStName() {
                    return stName;
                }

                /**
                 * Sets the value of the stName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStName(String value) {
                    this.stName = value;
                }

                /**
                 * Gets the value of the stCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStCode() {
                    return stCode;
                }

                /**
                 * Sets the value of the stCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStCode(String value) {
                    this.stCode = value;
                }

            }

        }

    }

}
